name: Image

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"

env:
  IMAGE_REF: 'nafigat0r/ghost'

jobs:
  docker:
    name: Create image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    environment: production
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: '0'

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f #v4.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up vars
        run: |
          echo "IMAGE_TAG=$(git tag --sort=version:refname | tail -n1 | sed -e 's/v//')" >> $GITHUB_ENV
          echo "REVISION=$(git log -n 1 --format=%h)" >> $GITHUB_ENV

      - name: Build image
        run: |
          echo "Build tag $IMAGE_TAG"
          make image
          docker image tag ${{ env.IMAGE_REF }}:${{ env.IMAGE_TAG }} ${{ env.IMAGE_REF }}:latest

      - name: Set up build time
        run: |
          echo "BUILD_TIME=$(docker inspect ${{ env.IMAGE_REF }}:${{ env.IMAGE_TAG }} | grep -oP '(?<=Created\": \")[^\"]*')" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 #v0.36.0
        with:
          image-ref: ${{ env.IMAGE_REF }}:latest
          format: sarif
          output: trivy-results.sarif
          ignore-unfixed: true
          scan-type: image
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload trivy SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4.27.3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: trivy-results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: trivy

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_REF }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_REF }}:latest

      - name: Crane setup
        uses: imjasonh/setup-crane@feee3b6bb0d4c68370f256a4502498c9227e5c6b # v0.7
        with:
          version: v0.21.7

      - name: Annotate
        run: |
          crane mutate \
            --annotation "org.opencontainers.image.revision=${{ env.REVISION }}" \
            --annotation "org.opencontainers.image.created=${{ env.BUILD_TIME }}" \
            --annotation "org.opencontainers.image.title=ghost" \
            --annotation "org.opencontainers.image.ref.name=${{ env.IMAGE_TAG }}" \
            --annotation "org.opencontainers.image.version=${{ env.IMAGE_TAG }}" \
            --annotation "org.opencontainers.image.description=Go Hi-level Open Service Templater. Utility for creating Go microservice template in a workdir." \
            --annotation "org.opencontainers.image.authors=alex@itvault.info" \
            --annotation "org.opencontainers.image.vendor=Alexander Yancharuk" \
            --annotation "org.opencontainers.image.licenses=MIT" \
            --annotation "org.opencontainers.image.url=https://github.com/nafigator/ghost/blob/${{ env.REVISION }}/README.md" \
            --annotation "org.opencontainers.image.source=https://github.com/nafigator/ghost/blob/${{ env.REVISION }}/.docker/Dockerfile" \
            ${{ env.IMAGE_REF }}:${{ env.IMAGE_TAG }}
          crane mutate \
            --annotation "org.opencontainers.image.revision=${{ env.REVISION }}" \
            --annotation "org.opencontainers.image.created=${{ env.BUILD_TIME }}" \
            --annotation "org.opencontainers.image.title=ghost" \
            --annotation "org.opencontainers.image.ref.name=latest" \
            --annotation "org.opencontainers.image.version=${{ env.IMAGE_TAG }}" \
            --annotation "org.opencontainers.image.description=Go Hi-level Open Service Templater. Utility for creating Go microservice template in a workdir." \
            --annotation "org.opencontainers.image.authors=alex@itvault.info" \
            --annotation "org.opencontainers.image.vendor=Alexander Yancharuk" \
            --annotation "org.opencontainers.image.licenses=MIT" \
            --annotation "org.opencontainers.image.url=https://github.com/nafigator/ghost/blob/${{ env.REVISION }}/README.md" \
            --annotation "org.opencontainers.image.source=https://github.com/nafigator/ghost/blob/${{ env.REVISION }}/.docker/Dockerfile" \
            ${{ env.IMAGE_REF }}:latest

      - name: Create release
        env:
          GOOS: linux
          GOARCH: amd64
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          docker cp "$(docker create ${{ env.IMAGE_REF }}:${{ env.IMAGE_TAG }}):/usr/local/sbin/ghost" - \
            | gzip -9 > /tmp/${{ env.GOOS }}-${{ env.GOARCH }}.tar.gz
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --generate-notes \
            "/tmp/${{ env.GOOS }}-${{ env.GOARCH }}.tar.gz"
