name: Image

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: '0'

      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up tag
        run: echo "IMAGE_TAG=$(git tag --sort=version:refname | tail -n1 | sed -e 's/v//')" >> $GITHUB_ENV

      - name: Build & push image
        run: |
          echo "Build with $IMAGE_TAG"
          make image
          docker image tag nafigat0r/ghost:$IMAGE_TAG nafigat0r/ghost:latest
          docker push nafigat0r/ghost:$IMAGE_TAG
          docker push nafigat0r/ghost:latest
